version: '3.8'
services:
  auth:
    build:
      context: ./apps/auth
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db_url_shortener?schema=auth
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./apps/auth:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - db
    entrypoint: ["sh", "-c", "npm install && npx prisma migrate deploy && nodemon --watch src --exec 'npm run start:dev'"]

  url-shortener:
    build:
      context: ./apps/url-shortener
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db_url_shortener?schema=url_shortener
    ports:
      - "3001:3000"
    networks:
      - app-network
    volumes:
      - ./apps/url-shortener:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - db
      - auth
    entrypoint: ["sh", "-c", "npm install && npx prisma migrate deploy && nodemon --watch src --exec 'npm run start:dev'"]

  # gateway:
  #   build:
  #     context: ./gateway
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - auth
  #     - url-shortener

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes:
  postgres_data:
    driver: local
